### ISSUE TITLE
GriefPrevention dosen't work on Islands after a Server restart.

### ISSUE THREAD

**Issue by MissingNo3L** [aleksilassila/Islands#25] opened 2021-05-29 00:39 UTC
The Islands plugin is amazing and it works well, but I am having problems with GriefPrevention, its protecting island by default but after a server restart anything we do on our island will just say "You can't build here unless you claim some land first." which removes the Protection of public Islands and anyone can claim on it, is there a reason why Grief Prevention is acting like this or is something in GriefPrevention thats the cause?

**Comment by aleksilassila** [comment] 2021-06-08 19:45
Did you solve this? I've ran into similar issues before, I'll see what I can do if the issue is still present

**Comment by MissingNo3L** [comment] 2021-06-10 17:28
sadly I had to remove grief prevention.

**Comment by GreyHammond** [comment] 2021-07-10 17:08
Posting here because I'm having the same issue.

When creating islands, players can enjoy the plugin with no issue.

Should the server restart at all, either by crash, console, or schedule, GP prevents anyone, including the island owner, from building breaking or any editing at all in their island.

A temporary fix is using GP's claiming system, however, after restart, players once again lose all access to edit their claims.

**Comment by aleksilassila** [comment] 2021-07-10 19:25
Will check this after a week

**Comment by GreyHammond** [comment] 2021-07-10 19:48
ok so, some digging

[19:42:16] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[19:42:16] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[19:42:17] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[19:42:24] [Server thread/INFO]: [Vault] [Economy] Essentials Economy hooked.
[19:42:24] [Server thread/INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[19:42:25] [Server thread/INFO]:   Permissions: TownyPerms, LuckPerms 5.3.47 via Vault
[19:42:25] [Server thread/INFO]:   Economy: Essentials Economy via Vault
[19:42:25] [Server thread/ERROR]: [Islands] No Vault found. Some permissions disabled.
[19:42:25] [Server thread/INFO]: [Islands] No islands world found. Creating one called islands...

except... vault is installed, and the islands world HAS been created and is still being used.

perhaps upon restart it's not finding the islands, and causing griefprotection issues?

also, it's not hooking into the essentialx economy?

**Comment by GreyHammond** [comment] 2021-07-13 17:47
OMG.. I'm literally stupid.

There's nothing to suggest that Multiverse Core is required, except a curious note in the wiki, stating to use /mvimport...

reset everything to a clean environment and installed spigot, multiverse, GriefPreevents, void generator, edit configs, 

restart, add and edit islands, 

restart. everything APPEARS to be working properly.

EssentialsX has a bug with it's economy, so i also suggest recommending a different economy plugin. 

I use ultimateshops, vault, and SpigotEconomy to sell items to the server to generate funds for islands.

hope this helps, thanks!

**Comment by aleksilassila** [comment] 2021-12-10 07:20
Tested and working with the latest dev versions of griefprevention in 1.18. If I recall correctly, the original issue had to do with a bug in GriefPrevention and should be now fixed. Someone reopen if there are issues regarding this still.

**Closed by aleksilassila** 2021-12-10 07:20 UTC
