### ISSUE TITLE
is commands do not work in 1.18 Paper

### ISSUE THREAD

**Issue by pokemonrocks9** [aleksilassila/Islands#32] opened 2021-12-04 03:04 UTC
running /is home does not allow one to go home anymore

**Comment by pokemonrocks9** [comment] 2021-12-04 14:25
correction. All commands no longer work. The island plugin loads and generates a world if its not there but does not allow commands

**Comment by victordestroyer** [comment] 2021-12-04 16:25
Same here, except that the plugin also does not TP me to the wilderness world after jumping off the side of an island, so I just fall into the void and die.

**Comment by aleksilassila** [comment] 2021-12-04 17:59
Please attach your server logs. I'll update the plugin to 1.18 in upcoming weeks

**Comment by pokemonrocks9** [comment] 2021-12-04 18:32
Common occurrence in 1.18
 Task #101 for Islands v5.0.8 generated an exception
But due to our host having to revert back to 1.17 via backup (we had
plugins straight up not work) we lost the logs. Later I can most likely run
this on a personal rig and get you the error

**Comment by aleksilassila** [comment] 2021-12-04 19:38
Alright, well if you are certain that the error is because of 1.18 then I don't think there is need as I can just reproduce the issue by myself later

**Comment by victordestroyer** [comment] 2021-12-04 20:49
Once I get home, I should be able to test the plugin with just itself and the latest version of paper.

**Comment by aleksilassila** [comment] 2021-12-10 07:01
The plugin did load for me just fine, but there were some issues with the new biomes indeed. Will be fixed in next version.

**Closed by aleksilassila** 2021-12-10 07:01 UTC
